- name: demonstrates reading varible from external varible file
  #hosts: all
  hosts: localhost
  vars_files:
    - contacts

  tasks:
   - name: print the contacts
     debug: msg="Mobile number of {{item.value.name}} is {{item.value.mobile}}"
     with_dict: "{{my_contacts}}"

   - name: print the contacts
     debug: msg="Mobile number of {{item.value.name}} is {{item.value.mobile}}"
     with_dict: "{{other_contacts}}"
