- name: This playbook installs, configures and deploys web page in nginx server
  hosts: all
  #gather_facts: no
  vars:
    - greet_message: "DevOps"
    - provisoner_tool: "Docker"
    - automation_tool: "Ansible"
  tasks:
   - name: Install nginx in Ubuntu server
     apt: name=nginx update_cache=yes state=present
     when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

   - name: Install epel-release package in CentOs server
     yum: name=epel-release state=present
     when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

   - name: Install nginx in CentOs server
     yum: name=nginx state=present
     when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

   - name: Create the web root folder
     shell: "mkdir -p /var/html"

   - name: Modify the web root folder permision
     shell: "chmod 777 /var/html"

   - name: Configure nginx web root folder in Ubuntu
     copy: src=default_ubuntu dest=/etc/nginx/sites-available/default
     when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
     notify:
       - Restart nginx server in Ubuntu

   - name: Configure nginx web root folder in CentOS
     copy: src=centos.conf dest=/etc/nginx/nginex.conf
     when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
     notify:
      - Restart nginx server in CentOS

   - name: Deploy web page in nginx server 
     template: src=index.html.j2 dest=/var/html/index.html
     notify:
      - Restart nginx server in CentOS
      - Restart nginx server in Ubuntu

  handlers:
   - name: Restart nginx server in CentOS
     service: name=nginx state=restarted 

   - name: Restart nginx server in Ubuntu
     shell: "/etc/init.d/nginx restart" 
