---
- import_playbook: start_ubuntu.yml
- import_playbook: start_CentOs.yml

- name: This playnook makes use of our custom nginx role
  hosts: all
  vars:
   task_status: not_running   
  roles:
   - nginx

  pre_tasks:
    - debug: msg="This is a pre task - may be you can start your contianer here"

  tasks:
    - name: set the task_status to running
      set_fact: 
       task_status: running   
        
   
    - name: Print the task_status value
      debug: var=task_status

  post_tasks:
    - debug: msg="This is post task - Maybe you can stop or remove your containers here" 
