---
- name: Start the docker container here
  hosts: localhost

  tasks:
   - name: Start the ubuntu container
     docker_container:
      image: verizon/ansible-ubuntu
      state: present
      name: "ubuntu{{item}}"
      ports:
         - "200{{item}}:22"
         - "800{{item}}:80"
     with_sequence: start=1 end=2
