---
- name: Start the docker container here
  hosts: localhost
  tasks:
   - name: Start the Centos container
     docker_container:
       image: verizon/ansible-centos
       state: present
       name: "centos{{item}}"
       ports:
         - "300{{item}}:22"
         - "900{{item}}:80"
     with_sequence: start=1 end=2
