- name: Demonstrates spinning up new containers through playbooks
  hosts: localhost

  tasks:
   - name: Start new docker ubuntu container
     docker_container:
      image: verizon/ansible-ubuntu 
      name: "ubuntu{{item}}"
      state: started
      ports:
       - "200{{item}}:22"
       - "800{{item}}:80"
     with_sequence: start=1 end=2
     
   - name: Start new docker CentOs container
     docker_container:
      image: verizon/ansible-centos
      name: "centos{{item}}"
      state: started
      ports:
       - "300{{item}}:22"
       - "900{{item}}:80"
     with_sequence: start=1 end=2
